### ISSUE TITLE
MouseState isn't working

### ISSUE THREAD

**Issue by ccorcos** [danomatika/BangYourHead#1]
I'm new to pd as you can imaging and I can't figure out why MouseData isn't working...

I checked the path in preferences and this guy points right to cyclone. The help opens as well, but none of the interactions work.

<img width="680" alt="screen shot 2017-12-26 at 5 53 52 pm" src="https://user-images.githubusercontent.com/1794527/34368051-bd653118-ea65-11e7-8033-c0b4753c78a9.png">

I'm on a MacBook Pro.

**Comment by danomatika** [comment]
That sounds like a problem with the Cyclone external library. It looks like you are using Purr Data as opposed to Pd "vanilla" and there may be a difference in how Cyclone is loaded/works. I don't know as I use neither Purr Data or Cyclone.

This repository is for various patches I use for teaching Pd vanilla and does not use Cyclone. Your best option is to send an email to the pd-list and/or open an issue on the Cyclone Github repo.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by ccorcos** [comment]
I see. Well thanks anyways.

**Comment by danomatika** [comment]
Sorry. Actually, you are correct. I forgot the Keyboard & Mouse patch uses cyclone. I updated the instructions in the patch on how to make sure the path is setup when using Pd vanilla.

As for Purr Data, that is beyond me as I've not used it extensively. I would first check whether cyclone objects open at all (help patches, etc) and which version of cyclone you are using. The version distributed with Purr Data may be old and not have the MouseState object, I don't know.
